const data = [
    {id: "musicians", results:[ { resNo: 1, content: { link: "http://whitneyhouston.com", name: "Whitney Houston", description: "When she passed on at an early age, fans mourned internationally. We honored her life with many documentaries and biographical films and she kept stacking up even more awards posthumously, further entrenching her record in that regard. "}},
                                { resNo: 2, content: { link: "http://queen.com", name: "Queen", description: "Since 2004, they've been touring again under the name \"Queen\" with Paul Rodgers and Adam Lambert as their vocalists. Though they've recorded 15 studio albums, they've had 21 tours of concerts. They even have a musical based on their music."}},
                                { resNo: 3, content: { link: "http://theeagles.com", name: "The Eagles", description: "One member of The Eagles was fired from the group after demanding a higher percentage of the group's profits instead of the even 5-way split they'd had since day one. He later sued for other reasons as revenge and tried to get $50 million in damages. The judge dismissed the case outright."}},
                                { resNo: 4, content: { link: "http://mariahcarey.com", name: "Mariah Carey", description: "If you ask Mariah Carey, she\'ll tell you that she's an alto, but music critics and professionals give her the label of a Coloratura soprano. She says she can reach her highest notes due to polyps on her vocal cords. Her Christmas song \'All I Want for Christmas is You\' is nearly the quintessential song for the season now."}},
                                { resNo: 5, content: { link: "http://thebeatles.com", name: "The Beatles", description: "Since 2001, the date of January 16th is recognized as World Beatles Day under UNESCO. There are 5 asteroids named after each band member and the band itself. Eric Clapton was almost the Fifth Beatle at one time.l"}},
                                { resNo: 6, content: { link: "http://elvispresley.com", name: "Elvis Presley", description: "Elvis Presley was drafted into military service in 1958 at the height of his career. He was awarded the Presidential Medal of Freedom posthumously in 2018. His home Graceland became the 2nd most visited home in the US after the White House. It's a National Historic Landmark since 2006."}},
                                { resNo: 7, content: { link: "http://michaeljackson.com", name: "Michael Jackson",  description: "Michael Jackson's estate still brings in around $825 million a year, the highest amount for any celebrity of any kind. He once won 8 Grammys in one ceremony, tied for the record with the band Santana. During the Thriller years he had the highest royalty rate in the music industry at $2 per sale."}},
                                { resNo: 8, content: { link: "http://eltonjohn.com", name: "Elton John", description: "Sir Elton John's middle name is Hercules. He was born as Reginald Kenneth Dwight. He's was knighted in 1998 for his services to music and charitable services. He's performed at many royal events at Westminster Abbey and Buckingham Palace. "}},
                                { resNo: 9, content: { link: "http://madonna.com", name: "Madonna", description: "Madonna is the highest grossing solo artist of all time, the most-touring female musician ever, and the best-selling female recording artist of all time, globally. In the USA, she's only second behind Barbara Streisand."}},
                                { resNo:10, content: { link: "http://ledzeppelin.com", name: "Led Zeppelin",  description: "Led Zeppelin worked in a time before the internet existed. It's been almost 40 years since their last album, and the internet's combined mind power has come to realize just how many of their songs they \"plagiarized,\" if not were heavily influenced by"}}
                            ]},
    {id: "painters", results:[ { resNo: 1, content: { link: "http://leonardodavinci .com", name: "Leonardo da Vinci ", description: "Not only did Leonardo da Vinci experiment with mediums, but he also innovated different ways of creating striking compositions. In fact, his signature triangular composition is still used today and is widely considered one of the most visually pleasing painting layouts. "}},
                                { resNo: 2, content: { link: "http:/michelangelo.com", name: "Michelangelo", description: "Though relatively few Michelangelo paintings survive, those that do are considered some of the best in the world. His ability to quickly master fresco painting and take it to new heights is evident in both the Sistine Chapel Ceiling and The Last Judgement, which continue to inspire artists today."}},
                                { resNo: 3, content: { link: "http://rembrandtvanrijn.com", name: "Rembrandt van Rijn", description: "Rembrandt van Rijn is so famous that even today we call this Dutch master by his first name. Painting everything from genre scenes to landscapes to great historical and mythological paintings, Rembrandt was the dominant force in Dutch art for much of the 17th century. "}},
                                { resNo: 4, content: { link: "http://vincentvangogh.com", name: "Vincent van Gogh", description: "Though he is seen today as one of the most influential painters in Western art, Vincent van Gogh was not commercially successful during his lifetime. Since the early 20th century, however, his masterful paintings have been prized for their expressive emotion. The Post-Impressionist painter's artwork is a roadmap to modern art."}},
                                { resNo: 5, content: { link: "http://claudemonet .com", name: "Claude Monet ", description: "Claude Monet is perhaps the most beloved of all Impressionist painters. In fact, his painting Impression, Sunrise is credited with launching the entire art movement, and his series of water lilies is a part of his lasting legacy with over 250 iterations of the subject."}},
                                { resNo: 6, content: { link: "http://pablopicasso.com", name: " Pablo Picasso", description: "In an 80-year career that moves through multiple styles and over 20,000 works, Pablo Picasso is undoubtedly one of the most recognized names in Western art. His role in launching Cubism would be enough to cement his status in the history books, but Picasso did much more."}},
                                { resNo: 7, content: { link: "http://fridakahlo.com", name: "Frida Kahlo", description: "Her highly intimate series of self-portraits and the embracement of her cultural heritage are just some of the things that make Frida Kahlo one of the greatest painters of the 20th century. Today she has become a pop culture icon, but this shouldn't overshadow her great skill as a painter and her innovations in bringing Mexican culture to a wider audience. "}},
                                { resNo: 8, content: { link: "http://jacksonpollock.com", name: "Jackson Pollock", description: "American painter Jackson Pollock is best known for his innovative painting technique. By dripping paint on the canvas, the Abstract Expressionist created dynamic, abstract artwork that revolutionized the art scene."}},
                                { resNo: 9, content: { link: "http://paulcezanne.com", name: "Paul Cezanne", description: "Leading Post-Impressionist painter Paul Cézanne has enjoyed a lasting legacy thanks to his innovative approach to perspective, vivid color palette, and use of painterly brushstrokes that were meticulously arranged into geometric forms."}},
                                { resNo:10, content: { link: "http://josephmallordwilliamturner.com", name: "Joseph Mallord William Turner",  description: "British Romantic painter JMW Turner is known as a forerunner of modern art. Coming from traditional Neo-classical painting, Turner began striving for realism in his work—which was unheard of at the time. Through thousands of watercolors and oil paintings, he experimented with light, color, and brushwork."}}
                            ]}
]

module.exports = data;
