const data = [
    {id: "musicians", results:[ { resNo: 1, content: { link: "http://whitneyhouston.com", name: "Whitney Houston", sales: 136, description: "When she passed on at an early age, fans mourned internationally. We honored her life with many documentaries and biographical films and she kept stacking up even more awards posthumously, further entrenching her record in that regard. "}},
                                { resNo: 2, content: { link: "http://queen.com", name: "Queen", sales: 147.6, description: "Since 2004, they've been touring again under the name \"Queen\" with Paul Rodgers and Adam Lambert as their vocalists. Though they've recorded 15 studio albums, they've had 21 tours of concerts. They even have a musical based on their music."}},
                                { resNo: 3, content: { link: "http://theeagles.com", name: "The Eagles", sales: 149.9, description: "One member of The Eagles was fired from the group after demanding a higher percentage of the group's profits instead of the even 5-way split they'd had since day one. He later sued for other reasons as revenge and tried to get $50 million in damages. The judge dismissed the case outright."}},
                                { resNo: 4, content: { link: "http://mariahcarey.com", name: "Mariah Carey, sales: 171.9, description: \"If you ask Mariah Carey, she\'ll tell you that she's an alto, but music critics and professionals give her the label of a Coloratura soprano. She says she can reach her highest notes due to polyps on her vocal cords. Her Christmas song \'All I Want for Christmas is You\' is nearly the quintessential song for the season now."}},
                                { resNo: 5, content: { link: "http://thebeatles.com", name: "The Beatles", sales: 279.8, description: "Since 2001, the date of January 16th is recognized as World Beatles Day under UNESCO. There are 5 asteroids named after each band member and the band itself. Eric Clapton was almost the Fifth Beatle at one time.l"}},
                                { resNo: 6, content: { link: "http://elvispresley.com", name: "Elvis Presley", sales: 225.7, description: "Elvis Presley was drafted into military service in 1958 at the height of his career. He was awarded the Presidential Medal of Freedom posthumously in 2018. His home Graceland became the 2nd most visited home in the US after the White House. It's a National Historic Landmark since 2006."}},
                                { resNo: 7, content: { link: "http://michaeljackson.com", name: "Michael Jackson", sales: 232, description: "Michael Jackson's estate still brings in around $825 million a year, the highest amount for any celebrity of any kind. He once won 8 Grammys in one ceremony, tied for the record with the band Santana. During the Thriller years he had the highest royalty rate in the music industry at $2 per sale."}},
                                { resNo: 8, content: { link: "http://eltonjohn.com", name: "Elton John", sales: 189.6, description: "Sir Elton John's middle name is Hercules. He was born as Reginald Kenneth Dwight. He's was knighted in 1998 for his services to music and charitable services. He's performed at many royal events at Westminster Abbey and Buckingham Palace. "}},
                                { resNo: 9, content: { link: "http://madonna.com", name: "Madonna", sales: 173.8, description: "Madonna is the highest grossing solo artist of all time, the most-touring female musician ever, and the best-selling female recording artist of all time, globally. In the USA, she's only second behind Barbara Streisand."}},
                                { resNo:10, content: { link: "http://ledzeppelin.com", name: "Led Zeppelin", sales: 140.6 , description: "Led Zeppelin worked in a time before the internet existed. It's been almost 40 years since their last album, and the internet's combined mind power has come to realize just how many of their songs they \"plagiarized,\" if not were heavily influenced by"}}
                            ]}
];

module.exports = data;
